server:
  port: 8084

spring:
  application:
    name: ms-farmacia
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:clinica_farmacia}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
